name: 'Set up Nextcloud'
description: 'Set up a Nextcloud environment'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  nextcloud-version:
    description: 'Version tag or branch name to set up'
    required: false
    default: 'master'
  install:
    description: 'Run Nextcloud installation? Skip if you only need the code, not a process'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to set up'
    required: false
    default: '16'
  php-version:
    description: 'PHP version to set up'
    required: false
    default: '8.1'
  php-coverage:
    description: 'PHP coverage support'
    required: false
    default: 'none'
  tools:
    description: 'Optional tools to install separated by space. Available: krankerl'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout Nextcloud
      shell: bash
      run: git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ inputs.nextcloud-version }} nextcloud
    - name: Set up Node.js ${{ inputs.node-version }}
      if: ${{ inputs.node-version != 'false' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Set up php${{ inputs.php-version }}
      if: ${{ inputs.install != 'false' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: ${{ inputs.php-coverage }}
    - name: Install krankerl
      if: ${{ contains(inputs.tools, 'krankerl') }}
      shell: bash
      run: |
        wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl_0.13.0_amd64.deb
        sudo dpkg -i krankerl_0.13.0_amd64.deb
    - name: Install Nextcloud
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: php -f nextcloud/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
